apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app
  labels:
    app: bank-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
      - name: my-bank-app
        image: srinubabuthammisetti/staragile-bank-app
        ports:
        - containerPort: 8082

