---
- hosts: all
  become: true
  connection: ssh

  tasks:
    - name: updating server
      command: sudo apt update 

    - name: install docker 
      command: sudo apt install docker.io -y

    - name: starting docker service 
      command: sudo systemctl start docker 

    - name: run the bank-application
      command: sudo docker run -d -p 8085:8081 srinubabuthammisetti/bank-app
      
